// Mock data generators for supervisor dashboards
import {
  SupervisorUser,
  ShiftData,
  LineData,
  ProductionMetrics,
  DowntimeAlert,
} from '@/types/Supervisor';

export const mockAssemblyLines: LineData[] = [
  {
    id: 'ASM-001',
    name: 'Assembly Line 1',
    status: 'active',
    production: { target: 500, actual: 485, efficiency: 97 },
    machines: [
      {
        id: 'M001',
        name: 'Robot Arm 1',
        status: 'running',
        uptime: 95,
        downtime: 5,
        oee: 92,
        availability: 95,
        performance: 98,
        quality: 99,
      },
      {
        id: 'M002',
        name: 'Conveyor 1',
        status: 'running',
        uptime: 98,
        downtime: 2,
        oee: 95,
        availability: 98,
        performance: 97,
        quality: 98,
      },
      {
        id: 'M003',
        name: 'QC Station',
        status: 'running',
        uptime: 96,
        downtime: 4,
        oee: 93,
        availability: 96,
        performance: 95,
        quality: 100,
      },
      {
        id: 'M004',
        name: 'Packaging',
        status: 'idle',
        uptime: 85,
        downtime: 15,
        oee: 82,
        availability: 85,
        performance: 96,
        quality: 98,
      },
    ],
    shift: {
      startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      supervisor: 'John Smith',
    },
  },
  {
    id: 'ASM-002',
    name: 'Assembly Line 2',
    status: 'active',
    production: { target: 500, actual: 502, efficiency: 100 },
    machines: [
      {
        id: 'M005',
        name: 'Robot Arm 2',
        status: 'running',
        uptime: 98,
        downtime: 2,
        oee: 96,
        availability: 98,
        performance: 99,
        quality: 99,
      },
      {
        id: 'M006',
        name: 'Conveyor 2',
        status: 'running',
        uptime: 97,
        downtime: 3,
        oee: 94,
        availability: 97,
        performance: 96,
        quality: 99,
      },
      {
        id: 'M007',
        name: 'Welder 1',
        status: 'running',
        uptime: 94,
        downtime: 6,
        oee: 91,
        availability: 94,
        performance: 98,
        quality: 97,
      },
      {
        id: 'M008',
        name: 'Curing Oven',
        status: 'running',
        uptime: 99,
        downtime: 1,
        oee: 97,
        availability: 99,
        performance: 98,
        quality: 98,
      },
    ],
    shift: {
      startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      supervisor: 'Sarah Johnson',
    },
  },
  {
    id: 'ASM-003',
    name: 'Assembly Line 3',
    status: 'maintenance',
    production: { target: 500, actual: 0, efficiency: 0 },
    machines: [
      {
        id: 'M009',
        name: 'Hydraulic Press',
        status: 'maintenance',
        uptime: 0,
        downtime: 100,
        oee: 0,
        availability: 0,
        performance: 0,
        quality: 0,
      },
    ],
    shift: {
      startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      supervisor: 'Mike Davis',
    },
  },
];

export const mockProductionLines: LineData[] = [
  {
    id: 'PROD-001',
    name: 'Production Line A',
    status: 'active',
    production: { target: 1000, actual: 975, efficiency: 98 },
    machines: [
      {
        id: 'MP001',
        name: 'Extruder',
        status: 'running',
        uptime: 96,
        downtime: 4,
        oee: 93,
        availability: 96,
        performance: 97,
        quality: 99,
      },
      {
        id: 'MP002',
        name: 'Cooling Unit',
        status: 'running',
        uptime: 99,
        downtime: 1,
        oee: 97,
        availability: 99,
        performance: 98,
        quality: 99,
      },
      {
        id: 'MP003',
        name: 'Cutting Machine',
        status: 'running',
        uptime: 94,
        downtime: 6,
        oee: 91,
        availability: 94,
        performance: 96,
        quality: 99,
      },
    ],
    shift: {
      startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      supervisor: 'Lisa Chen',
    },
  },
  {
    id: 'PROD-002',
    name: 'Production Line B',
    status: 'active',
    production: { target: 1000, actual: 950, efficiency: 95 },
    machines: [
      {
        id: 'MP004',
        name: 'Injection Mold',
        status: 'running',
        uptime: 92,
        downtime: 8,
        oee: 89,
        availability: 92,
        performance: 95,
        quality: 98,
      },
      {
        id: 'MP005',
        name: 'Trimmer',
        status: 'error',
        uptime: 78,
        downtime: 22,
        oee: 72,
        availability: 78,
        performance: 90,
        quality: 96,
      },
    ],
    shift: {
      startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      supervisor: 'Robert Wilson',
    },
  },
];

export const mockProductionMetrics: ProductionMetrics = {
  totalProduction: 1960,
  targetProduction: 2000,
  efficiency: 98,
  oee: 94,
  downtime: 45,
  plannedDowntime: 20,
  unplannedDowntime: 25,
  timestamp: new Date().toISOString(),
};

export const mockDowntimeAlerts: DowntimeAlert[] = [
  {
    id: 'DT001',
    lineId: 'PROD-002',
    machineId: 'MP005',
    type: 'unplanned',
    severity: 'high',
    startTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    reason: 'Motor bearing failure',
    duration: 30,
    status: 'ongoing',
  },
  {
    id: 'DT002',
    lineId: 'ASM-003',
    type: 'planned',
    severity: 'medium',
    startTime: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    reason: 'Scheduled maintenance',
    duration: 120,
    status: 'ongoing',
  },
  {
    id: 'DT003',
    lineId: 'ASM-001',
    machineId: 'M004',
    type: 'unplanned',
    severity: 'low',
    startTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    reason: 'Sensor calibration',
    duration: 10,
    status: 'resolved',
  },
];

export const mockShift: ShiftData = {
  id: 'SHIFT-001',
  shiftNumber: 2,
  startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
  supervisor: {
    id: 'SUP001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    role: 'assembly_supervisor',
    assignedLines: ['ASM-001', 'ASM-002'],
  } as SupervisorUser,
  lines: mockAssemblyLines,
  production: mockProductionMetrics,
};

export const mockCurrentUser: SupervisorUser = {
  id: 'SUP001',
  name: 'John Smith',
  email: 'john.smith@company.com',
  role: 'assembly_supervisor',
  assignedLines: ['ASM-001', 'ASM-002'],
  department: 'assembly',
};
